name: .Net
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore
      run: dotnet restore ./FarmFresh/FarmFresh.sln
    - name: Build
      run: dotnet build ./FarmFresh/FarmFresh.sln --no-restore
    - name: Test
      run: dotnet test ./FarmFresh/FarmFresh.sln --no-build --verbosity normal
